
ALTER TABLE donor_info
ADD COLUMN donorMobile BIGINT NOT NULL,
ADD COLUMN donorEmail VARCHAR(255) NOT NULL,
ADD COLUMN donorState VARCHAR(255) NOT NULL,
ADD COLUMN donorDistrict VARCHAR(255) NOT NULL,
ADD COLUMN donorAltNo BIGINT NOT NULL;

